import { Data, IProductInput, IUserInput, ICategoryInput } from '@/types'
import { toSlug } from './utils'
import bcrypt from 'bcryptjs'
import { i18n } from '@/i18n-config'

const users: IUserInput[] = [
  {
    name: 'John',
    email: 'admin@example.com',
    password: bcrypt.hashSync('Admin@2024!', 5),
    role: 'Admin',
    address: {
        fullName: 'John Doe',
      street: '111 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10001',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jane',
    email: 'jane@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Jane Harris',
      street: '222 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1002',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'CashOnDelivery',
    emailVerified: false,
  },
  {
    name: 'Jack',
    email: 'jack@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Jack Ryan',
      street: '333 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1003',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Sarah',
    email: 'sarah@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Sarah Smith',
      street: '444 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1005',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'CashOnDelivery',
    emailVerified: false,
  },
  {
    name: 'Michael',
    email: 'michael@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'John Alexander',
      street: '555 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1006',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Emily',
    email: 'emily@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Emily Johnson',
      street: '666 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10001',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Alice',
    email: 'alice@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Alice Cooper',
      street: '777 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10007',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'CashOnDelivery',
    emailVerified: false,
  },
  {
    name: 'Tom',
    email: 'tom@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Tom Hanks',
      street: '888 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10008',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Linda',
    email: 'linda@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Linda Holmes',
      street: '999 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10009',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'George',
    email: 'george@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'George Smith',
      street: '101 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10010',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jessica',
    email: 'jessica@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Jessica Brown',
      street: '102 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10011',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'CashOnDelivery',
    emailVerified: false,
  },
  {
    name: 'Chris',
    email: 'chris@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Chris Evans',
      street: '103 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10012',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Samantha',
    email: 'samantha@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Samantha Wilson',
      street: '104 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10013',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'David',
    email: 'david@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'David Lee',
      street: '105 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10014',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'CashOnDelivery',
    emailVerified: false,
  },
  {
    name: 'Anna',
    email: 'anna@example.com',
    password: bcrypt.hashSync('User@2024!', 5),
    role: 'User',
    address: {
      fullName: 'Anna Smith',
      street: '106 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10015',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
]

const categories: ICategoryInput[] = [
  // Catégories principales
  {
    name: 'Équipement informatique',
    slug: 'computer-equipment',
    description:
      'Ordinateurs, moniteurs, imprimantes et accessoires informatiques',
    image: '/images/categories/computer-equipment.jpg',
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Surveillance vidéo',
    slug: 'video-surveillance',
    description: 'Systèmes de surveillance vidéo et caméras de sécurité',
    image: '/images/categories/video-surveillance.jpg',
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Téléphonie',
    slug: 'telephony',
    description: 'Solutions de téléphonie IP et équipements de communication',
    image: '/images/categories/telephony.jpg',
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Sécurité incendie',
    slug: 'fire-safety',
    description: 'Équipements de sécurité incendie et détecteurs',
    image: '/images/categories/fire-safety.jpg',
    isActive: true,
    sortOrder: 4,
  },

  // Sous-catégories pour Équipement informatique
  {
    name: 'Moniteurs',
    slug: 'monitors',
    description: 'Écrans et moniteurs pour ordinateurs',
    image: '/images/p12-1.jpg',
    parentCategory: 'computer-equipment', // Référence vers la catégorie parent
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Ordinateurs de bureau',
    slug: 'desktop-computers',
    description: 'Ordinateurs de bureau et stations de travail',
    image: '/images/p13-1.jpg',
    parentCategory: 'computer-equipment',
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Ordinateurs portables',
    slug: 'laptops',
    description: 'Ordinateurs portables et notebooks',
    image: '/images/p14-1.jpg',
    parentCategory: 'computer-equipment',
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Imprimantes',
    slug: 'printers',
    description: 'Imprimantes et scanners',
    image: '/images/p15-1.jpg',
    parentCategory: 'computer-equipment',
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Stockage',
    slug: 'storage',
    description: 'Disques durs, SSD et stockage externe',
    image: '/images/p16-1.jpg',
    parentCategory: 'computer-equipment',
    isActive: true,
    sortOrder: 5,
  },

  // Sous-catégories pour Surveillance vidéo
  {
    name: 'IP Cameras',
    slug: 'ip-cameras',
    description: 'Caméras IP et caméras de surveillance réseau',
    image: '/images/p11-1.jpg',
    parentCategory: 'video-surveillance',
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Analog Cameras',
    slug: 'analog-cameras',
    description: 'Caméras analogiques et systèmes traditionnels',
    image: '/images/p17-1.jpg',
    parentCategory: 'video-surveillance',
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'DVR/NVR Systems',
    slug: 'dvr-nvr-systems',
    description: 'Enregistreurs vidéo numériques et réseau',
    image: '/images/p18-1.jpg',
    parentCategory: 'video-surveillance',
    isActive: true,
    sortOrder: 3,
  },

  // Sous-catégories pour Téléphonie
  {
    name: 'IP Phones',
    slug: 'ip-phones',
    description: 'Téléphones IP et équipements VoIP',
    image: '/images/p19-1.jpg',
    parentCategory: 'telephony',
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'PBX Systems',
    slug: 'pbx-systems',
    description: 'Systèmes PBX et centrales téléphoniques',
    image: '/images/p20-1.jpg',
    parentCategory: 'telephony',
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Headsets',
    slug: 'headsets',
    description: 'Casques et accessoires téléphoniques',
    image: '/images/p21-1.jpg',
    parentCategory: 'telephony',
    isActive: true,
    sortOrder: 3,
  },

  // Sous-catégories pour Sécurité incendie
  {
    name: 'Fire Extinguishers',
    slug: 'fire-extinguishers',
    description: "Extincteurs et équipements de lutte contre l'incendie",
    image: '/images/p22-1.jpg',
    parentCategory: 'fire-safety',
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Smoke Detectors',
    slug: 'smoke-detectors',
    description: 'Détecteurs de fumée et alarmes incendie',
    image: '/images/p23-1.jpg',
    parentCategory: 'fire-safety',
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Fire Alarms',
    slug: 'fire-alarms',
    description: "Systèmes d'alarme incendie et panneaux de contrôle",
    image: '/images/p24-1.jpg',
    parentCategory: 'fire-safety',
    isActive: true,
    sortOrder: 3,
  },
]

const products: IProductInput[] = [
  {
    name: 'Hikvision Dome Camera 4MP IP Security Camera',
    slug: toSlug('Hikvision Dome Camera 4MP IP Security Camera'),
    category: 'Surveillance vidéo',
    subCategory: 'IP Cameras',
    images: ['/images/p11-1.jpg', '/images/p11-2.jpg'],
    tags: ['new-arrival', 'featured', 'todays-deal'],
    isPublished: true,
    price: 89.99,
    listPrice: 129.99,
    brand: 'Hikvision',
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 11,
    description:
      'Caméra de surveillance IP 4MP avec vision nocturne, détection de mouvement et résistance IP67. Parfaite pour la surveillance intérieure et extérieure.',
    specifications: [
      '4MP Resolution',
      'Night Vision',
      'Motion Detection',
      'IP67 Waterproof',
      '2.8mm Fixed Lens',
      'H.265+ Compression',
      'Built-in Microphone',
      'Power over Ethernet (PoE)',
    ],
    compatibility: [
      'Hikvision NVR',
      'Universal ONVIF',
      'Hikvision App',
      'Web Browser',
    ],
    colors: ['White', 'Black'],
    reviews: [],
  },
  {
    name: 'Dahua IP Camera 2MP Bullet Security Camera',
    slug: toSlug('Dahua IP Camera 2MP Bullet Security Camera'),
    category: 'Surveillance vidéo',
    subCategory: 'IP Cameras',
    images: [
      '/images/p12-1.jpg',
      '/images/p12-2.jpg',
      '/images/p12-3.jpg',
      '/images/p12-4.jpg',
    ],
    tags: ['featured', 'best-seller'],
    isPublished: true,
    price: 67.99,
    listPrice: 89.99,
    brand: 'Dahua',
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 29,
    countInStock: 12,
    description:
      "Caméra de surveillance IP bullet 2MP avec vision nocturne jusqu'à 30m, détection de mouvement intelligente et résistance IP67. Idéale pour la surveillance extérieure.",
    specifications: [
      '2MP Resolution',
      'Night Vision 30m',
      'Smart Motion Detection',
      'IP67 Waterproof',
      '3.6mm Fixed Lens',
      'H.264+ Compression',
      'Built-in IR LEDs',
      'Power over Ethernet (PoE)',
    ],
    compatibility: ['Dahua NVR', 'Universal ONVIF', 'Dahua App', 'Web Browser'],
    colors: ['Black', 'White'],
    reviews: [],
  },
  {
    name: 'Samsung 24" LED Monitor Full HD',
    slug: toSlug('Samsung 24 LED Monitor Full HD'),
    category: 'Équipement informatique',
    subCategory: 'Monitors',
    brand: 'Samsung',
    images: ['/images/p13-1.jpg', '/images/p13-2.jpg'],
    tags: ['best-seller', 'featured'],
    isPublished: true,
    price: 149.99,
    listPrice: 199.99,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 55,
    countInStock: 13,
    description:
      'Moniteur LED Samsung 24 pouces avec résolution Full HD 1920x1080, temps de réponse 5ms et design ultra-fin. Parfait pour le travail, la bureautique et les jeux occasionnels.',
    specifications: [
      '24" Display',
      'Full HD 1920x1080',
      '5ms Response Time',
      'VGA/HDMI Ports',
      '60Hz Refresh Rate',
      '250 cd/m² Brightness',
      '1000:1 Contrast Ratio',
      '178° Viewing Angle',
    ],
    compatibility: [
      'Windows',
      'macOS',
      'Linux',
      'Universal',
      'HDMI 1.4',
      'VGA',
    ],
    colors: ['Black', 'Silver'],
    reviews: [],
  },
  {
    name: 'Dell OptiPlex 7090 Desktop Computer',
    slug: toSlug('Dell OptiPlex 7090 Desktop Computer'),
    category: 'Équipement informatique',
    subCategory: 'Desktop Computers',
    brand: 'Dell',
    images: ['/images/p14-1.jpg', '/images/p14-2.jpg'],
    tags: ['new-arrival', 'best-seller', 'todays-deal'],
    isPublished: true,
    price: 899.99,
    listPrice: 1199.99,
    avgRating: 4.5,
    numReviews: 8,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 23,
    countInStock: 7,
    description:
      'Ordinateur de bureau Dell OptiPlex 7090 avec processeur Intel Core i5, 8GB RAM, 256GB SSD et Windows 11 Pro. Idéal pour les entreprises et la bureautique.',
    specifications: [
      'Intel Core i5-10500',
      '8GB DDR4 RAM',
      '256GB NVMe SSD',
      'Windows 11 Pro',
      'Intel UHD Graphics 630',
      'Gigabit Ethernet',
      'USB 3.2 Gen 1',
      'DisplayPort 1.4',
    ],
    compatibility: [
      'Windows 11',
      'Universal',
      'Dell Support',
      'Enterprise Software',
    ],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'HP LaserJet Pro M404n Printer',
    slug: toSlug('HP LaserJet Pro M404n Printer'),
    category: 'Équipement informatique',
    subCategory: 'Printers',
    brand: 'HP',
    images: ['/images/p15-1.jpg', '/images/p15-2.jpg'],
    tags: ['featured'],
    isPublished: true,
    price: 299.99,
    listPrice: 399.99,
    avgRating: 4.3,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 5 },
      { rating: 5, count: 6 },
    ],
    numSales: 34,
    countInStock: 9,
    description:
      "Imprimante laser HP LaserJet Pro M404n avec impression monochrome haute qualité, connectivité réseau et impression rapide jusqu'à 40 ppm.",
    specifications: [
      'Monochrome Laser',
      '40 ppm',
      'Network Ready',
      'Duplex Printing',
      '1200 x 1200 dpi',
      'Ethernet Port',
      'USB 2.0',
      '250-sheet Tray',
    ],
    compatibility: ['Windows', 'macOS', 'Linux', 'Universal', 'HP Smart App'],
    colors: ['White'],
    reviews: [],
  },
  {
    name: 'Cisco IP Phone 7841',
    slug: toSlug('Cisco IP Phone 7841'),
    category: 'Téléphonie',
    subCategory: 'IP Phones',
    brand: 'Cisco',
    images: ['/images/p16-1.jpg', '/images/p16-2.jpg'],
    tags: ['new-arrival', 'featured'],
    isPublished: true,
    price: 89.99,
    listPrice: 129.99,
    avgRating: 4.6,
    numReviews: 11,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 3 },
      { rating: 5, count: 7 },
    ],
    numSales: 18,
    countInStock: 14,
    description:
      'Téléphone IP Cisco 7841 avec écran LCD, support des codecs G.711 et G.729, et compatibilité avec les systèmes de téléphonie IP.',
    specifications: [
      'IP Phone',
      'LCD Display',
      'G.711/G.729 Codecs',
      'PoE Compatible',
      'Gigabit Ethernet',
      'HD Audio',
      'Programmable Keys',
      'Headset Port',
    ],
    compatibility: [
      'Cisco Call Manager',
      'Universal SIP',
      'Cisco IP Communicator',
      'Web Browser',
    ],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'Kidde Fire Extinguisher 10-B:C',
    slug: toSlug('Kidde Fire Extinguisher 10-B:C'),
    category: 'Sécurité incendie',
    subCategory: 'Fire Extinguishers',
    brand: 'Kidde',
    images: ['/images/p21-1.jpg', '/images/p21-2.jpg'],
    tags: ['best-seller', 'featured', 'todays-deal'],
    isPublished: true,
    price: 45.99,
    listPrice: 59.99,
    avgRating: 4.8,
    numReviews: 25,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 4 },
      { rating: 5, count: 20 },
    ],
    numSales: 67,
    countInStock: 22,
    description:
      "Extincteur d'incendie Kidde 10-B:C avec agent chimique sec, poignée ergonomique et indicateur de pression. Certifié UL et CSA.",
    specifications: [
      '10-B:C Rating',
      'Dry Chemical',
      'Pressure Gauge',
      'UL/CSA Certified',
      '2.5 lb Capacity',
      'Easy-grip Handle',
      'Metal Valve',
      'Wall Mount Bracket',
    ],
    compatibility: [
      'Universal',
      'Commercial Use',
      'Residential Use',
      'Vehicle Use',
    ],
    colors: ['Red'],
    reviews: [],
  },
  {
    name: 'First Alert Smoke Detector Battery Powered',
    slug: toSlug('First Alert Smoke Detector Battery Powered'),
    category: 'Sécurité incendie',
    subCategory: 'Smoke Detectors',
    brand: 'First Alert',
    images: ['/images/p22-1.jpg', '/images/p22-2.jpg'],
    tags: ['new-arrival', 'best-seller'],
    isPublished: true,
    price: 19.99,
    listPrice: 29.99,
    avgRating: 4.4,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 5 },
      { rating: 5, count: 10 },
    ],
    numSales: 45,
    countInStock: 31,
    description:
      'Détecteur de fumée First Alert alimenté par pile avec technologie photélectrique, bouton de test et alarme de 85 dB.',
    specifications: [
      'Photoelectric Technology',
      '85 dB Alarm',
      'Battery Powered',
      'Test Button',
      'Low Battery Indicator',
      'Hush Feature',
      'Tamper-resistant Design',
      '10-Year Warranty',
    ],
    compatibility: [
      'Universal',
      'Residential Use',
      'Commercial Use',
      '9V Battery',
    ],
    colors: ['White'],
    reviews: [],
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon Laptop',
    slug: toSlug('Lenovo ThinkPad X1 Carbon Laptop'),
    category: 'Équipement informatique',
    subCategory: 'Laptops',
    brand: 'Lenovo',
    images: ['/images/p23-1.jpg', '/images/p23-2.jpg'],
    tags: ['featured', 'premium'],
    isPublished: true,
    price: 1499.99,
    listPrice: 1899.99,
    avgRating: 4.7,
    numReviews: 16,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 3 },
      { rating: 5, count: 12 },
    ],
    numSales: 12,
    countInStock: 5,
    description:
      'Ordinateur portable Lenovo ThinkPad X1 Carbon avec processeur Intel Core i7, 16GB RAM, 512GB SSD et écran 14" 4K. Ultra-léger et ultra-performant.',
    specifications: [
      'Intel Core i7-1165G7',
      '16GB LPDDR4X RAM',
      '512GB NVMe SSD',
      '14" 4K Display',
      'Intel Iris Xe Graphics',
      'Thunderbolt 4',
      'Wi-Fi 6',
      'Fingerprint Reader',
    ],
    compatibility: [
      'Windows 11',
      'Universal',
      'Lenovo Vantage',
      'Enterprise Software',
    ],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'Western Digital 2TB Internal Hard Drive',
    slug: toSlug('Western Digital 2TB Internal Hard Drive'),
    category: 'Équipement informatique',
    subCategory: 'Storage',
    brand: 'Western Digital',
    images: ['/images/p24-1.jpg', '/images/p24-2.jpg'],
    tags: ['best-seller'],
    isPublished: true,
    price: 59.99,
    listPrice: 79.99,
    avgRating: 4.2,
    numReviews: 22,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 6 },
      { rating: 5, count: 11 },
    ],
    numSales: 89,
    countInStock: 28,
    description:
      'Disque dur interne Western Digital 2TB avec interface SATA 6Gb/s, vitesse de rotation 7200 RPM et technologie IntelliPower.',
    specifications: [
      '2TB Capacity',
      'SATA 6Gb/s',
      '7200 RPM',
      'IntelliPower Technology',
      '64MB Cache',
      '3.5" Form Factor',
      'Low Power Consumption',
      '5-Year Warranty',
    ],
    compatibility: [
      'Windows',
      'macOS',
      'Linux',
      'Universal',
      'SATA III',
      'Backward Compatible',
    ],
    colors: ['Black'],
    reviews: [],
  },
]
const reviews = [
  {
    rating: 1,
    title: 'Poor quality',
    comment:
      'Very disappointed. The item broke after just a few uses. Not worth the money.',
  },
  {
    rating: 2,
    title: 'Disappointed',
    comment:
      "Not as expected. The material feels cheap, and it didn't fit well. Wouldn't buy again.",
  },
  {
    rating: 2,
    title: 'Needs improvement',
    comment:
      "It looks nice but doesn't perform as expected. Wouldn't recommend without upgrades.",
  },
  {
    rating: 3,
    title: 'not bad',
    comment:
      'This product is decent, the quality is good but it could use some improvements in the details.',
  },
  {
    rating: 3,
    title: 'Okay, not great',
    comment:
      'It works, but not as well as I hoped. Quality is average and lacks some finishing.',
  },
  {
    rating: 3,
    title: 'Good product',
    comment:
      'This product is amazing, I love it! The quality is top notch, the material is comfortable and breathable.',
  },
  {
    rating: 4,
    title: 'Pretty good',
    comment:
      "Solid product! Great value for the price, but there's room for minor improvements.",
  },
  {
    rating: 4,
    title: 'Very satisfied',
    comment:
      'Good product! High quality and worth the price. Would consider buying again.',
  },
  {
    rating: 4,
    title: 'Absolutely love it!',
    comment:
      'Perfect in every way! The quality, design, and comfort exceeded all my expectations.',
  },
  {
    rating: 4,
    title: 'Exceeded expectations!',
    comment:
      'Fantastic product! High quality, feels durable, and performs well. Highly recommend!',
  },
  {
    rating: 5,
    title: 'Perfect purchase!',
    comment:
      "Couldn't be happier with this product. The quality is excellent, and it works flawlessly!",
  },
  {
    rating: 5,
    title: 'Highly recommend',
    comment:
      "Amazing product! Worth every penny, great design, and feels premium. I'm very satisfied.",
  },
  {
    rating: 5,
    title: 'Just what I needed',
    comment:
      'Exactly as described! Quality exceeded my expectations, and it arrived quickly.',
  },
  {
    rating: 5,
    title: 'Excellent choice!',
    comment:
      'This product is outstanding! Everything about it feels top-notch, from material to functionality.',
  },
  {
    rating: 5,
    title: "Couldn't ask for more!",
    comment:
      "Love this product! It's durable, stylish, and works great. Would buy again without hesitation.",
  },
]

const data: Data = {
  users,
  products,
  reviews,
  categories,
  carousels: [
    {
      title: 'Systèmes de surveillance vidéo professionnels',
      buttonCaption: ' ',
      image: '/images/banner1.jpg',
      url: '/search?category=Surveillance vidéo',
      isPublished: true,
    },
    {
      title: 'Équipements de sécurité incendie',
      buttonCaption: ' ',
      image: '/images/banner2.jpg',
      url: '/search?category=Sécurité incendie',
      isPublished: true,
    },
    {
      title: "Meilleures offres sur l'équipement informatique",
      buttonCaption: ' ',
      image: '/images/banner3.jpg',
      url: '/search?category=Équipement informatique',
      isPublished: true,
    },
  ],
  settings: [
    {
      common: {
        isMaintenanceMode: false,
        defaultTheme: 'Light',
        defaultColor: 'Gold',
        pageSize: 9,
      },
      site: {
        name: 'MendelCorp',
        description:
          'MendelCorp est une plateforme de commerce électronique de premier plan spécialisée dans les produits technologiques de pointe, les équipements informatiques, les systèmes de sécurité et les solutions de téléphonie professionnelle.',
        keywords:
          'Technologie, Équipement informatique, Systèmes de sécurité, Téléphonie, Sécurité incendie, Équipement professionnel, MendelCorp',
        url: 'https://mendel-c.vercel.app/',
        logo: '/icons/logo.png',
        slogan: "Renforcer la technologie, sécuriser l'avenir.",
        author: 'MendelCorp',
        copyright: '2017-2024, MendelCorp.com.',
        email: 'admin@mendelcorp.com',
        address: "Cocody, Abidjan Côte d'Ivoire",
        phone: '+225 20 30 40 50',
      },
      carousels: [
        {
          title: 'Systèmes de surveillance vidéo professionnels',
          buttonCaption: ' ',
          image: '/images/banner1.jpg',
          url: '/search?category=Surveillance vidéo',
        },
        {
          title: 'Équipements de sécurité incendie',
          buttonCaption: ' ',
          image: '/images/banner2.jpg',
          url: '/search?category=Sécurité incendie',
        },
        {
          title: "Meilleures offres sur l'équipement informatique",
          buttonCaption: ' ',
          image: '/images/banner3.jpg',
          url: '/search?category=Équipement informatique',
        },
      ],
      availableLanguages: i18n.locales.map((locale) => ({
        code: locale.code,
        name: locale.name,
      })),
      defaultLanguage: 'fr',
      availableCurrencies: [
        {
          name: 'United States Dollar',
          code: 'USD',
          symbol: '$',
          convertRate: 1,
        },
        { name: 'Euro', code: 'EUR', symbol: '€', convertRate: 0.96 },
        {
          name: "Franc CFA (Afrique de l'Ouest)",
          code: 'XOF',
          symbol: 'CFA',
          convertRate: 655.957,
        },
      ],
      defaultCurrency: 'XOF',
      availablePaymentMethods: [{ name: 'CashOnDelivery', commission: 0 }],
      defaultPaymentMethod: 'CashOnDelivery',
      availableDeliveryDates: [
        {
          name: 'Tomorrow',
          daysToDeliver: 1,
          shippingPrice: 12.9,
        },
        {
          name: 'Next 3 Days',
          daysToDeliver: 3,
          shippingPrice: 6.9,
        },
        {
          name: 'Next 5 Days',
          daysToDeliver: 5,
          shippingPrice: 4.9,
        },
      ],
      defaultDeliveryDate: 'Next 5 Days',
    },
  ],
}

export default data
